require 'herorealms'
require 'decks'
require 'stdlib'
require 'timeoutai'
require 'hardai_2'
require 'aggressiveai'
--=======================================================================================================
--This lua file builds on lesson #1 but not lesson #2, I reused some elements from lesson #2 to save time.
--The 2nd player is an AI bot with a random charcter/build and player 1 would have a custom loadout.
--
--Instead of making a custon action as in lesson #2, a custom item is made. 
-- The process is identical to lesson #2 so I will be covering adding a faction to a card as well.
--=======================================================================================================
function setupGame(g)
	registerCards(g, {
        --Anytime you make a new card/skill/ability/armor you need to put them here to be registered before you can use it.
        teach_them_an_item_lesson_carddef()
	})

    standardSetup(g, {
        description = "Lesson #3: Custom Item Cards<br>Created by WardenSlayer.",
        playerOrder = { plid1, plid2 },
        ai = ai.CreateKillSwitchAi(createAggressiveAI(),  createHardAi2()),
        timeoutAi = createTimeoutAi(),
        opponents = { { plid1, plid2 } },
        players = {
            {
                id = plid1,
                startDraw = 3,
                name = "Lua Lesson Warrior",
                avatar="assassin",
                health = 50,
                cards = {
                    deck = {
                        --Here the custom item card is added to player 1's deck
                        { qty=2, card=teach_them_an_item_lesson_carddef()},
                        { qty=8, card=gold_carddef() },
                    },
                    skills = {
                        {qty = 1, card = thief_lift_carddef() },
                        {qty = 1, card = fighter_devastating_blow_carddef()},
                        {qty = 1, card = ranger_hunters_cloak_carddef()},
                    },
                    buffs = {
                        drawCardsCountAtTurnEndDef(5),
                        discardCardsAtTurnStartDef(),
                        fatigueCount(40, 1, "FatigueP1")
                    }
                }
            }, 
            {
                --Player 2 is an AI controlled player. They will have a random class/build each time
                --The AI is always the same level as the player's character.
                id = plid2,
                isAi = true,
                startDraw = 5,
				init = {
                    fromEnv = plid2
                },
                cards = {
					buffs = {
                        drawCardsCountAtTurnEndDef(5),
                        discardCardsAtTurnStartDef(),
						fatigueCount(40, 1, "FatigueP2"),
					}
                }
            },          
        }
    })
end

--=======================================================================================================
--When making a custom card of any type, it starts with a declaration function like this.
--There are 2 main steps to making a custom card.
--     1) Designing the layout of the card (to include the actual abilities the card has)
--     2) Coding the functionality of card
function teach_them_an_item_lesson_carddef()
    --This first section creates a card layout for use later on
	local cardLayout = createLayout({
        --This is the display text ont he card title
		name = "Teach Them an Item Lesson",
        --This sets the art that displays on card (you can find these in the art section of the Lua Doc)
		art = "art/treasures/T_Wizard_Elixir_Silver",
        --This sets the card frame/border art that displays on card (you can find these in the frames section of the Lua Doc)
		frame = "frames/Guild_Action_CardFrame",
        --This is the card type display text that appears at the top center of the card
		cardTypeLabel = "Item",
        --This part generates the card ability text that tells you what the card does
        --This xmlText was generated by using the card designer
        xmlText = [[
            <vlayout>
            <box flexibleheight="1">
               <tmpro text="{combat_4}" fontsize="36" />
            </box>
            <divider />
            <hlayout flexibleheight="1">
               <box flexiblewidth="1">
                  <tmpro text="{imperial}" fontsize="40" />
               </box>
               <box flexiblewidth="7">
                  <tmpro text="&lt;cspace=0.5em&gt;{health_5}&lt;/cspace&gt;" fontsize="40" />
               </box>
            </hlayout>
            <divider />
            <hlayout flexibleheight="1">
               <box flexiblewidth="1">
                  <tmpro text="{necro}" fontsize="36" />
               </box>
               <box flexiblewidth="7">
                  <tmpro text="Draw a card." fontsize="22" />
               </box>
            </hlayout>
         </vlayout>
                ]]
	})
	--This next section populated the object data for the card
    --and is how you control what the card can do
	return createItemDef({
        --The cards ID which can be used t identify it in other places
		id = "teach_them_an_item_lesson_card",
        --The card's name but not the one you see on the card image.
		name = "Teach Them an Item Lesson",
        --If you were to buy the card how much would it cost
		acquireCost = 0,
        --This is the card type display text that appears at the top center of the card
		cardTypeLabel = "Item",
        --Here you define what types the card has so it can interact with other cards
        --that do different things based on type
        --ItemType for items, noStealType is for starter cards or cards you dont want a thief to be able to steal
        --other exmaples (like meleeWeaponType or bowType) can befound in the card subtypes section of the Lua document)
		types = { itemType, noStealType },
        --Here is where you define the faction the card has. It will now trigger the
        --faction abilities of the type listed here.
        factions = {guildFaction},
        --Here we finally use the layout created above to set the visual display for the card
		layout = cardLayout,
        --Where the card is played, for items that is castPloc which is different then where champions are played
		playLocation = castPloc,
        --This last section creates object data to make the card work.
        --A card can have any number of abilities but this one has two.
		abilities = {
            --This ability triggers any time the card is played and gives 4 combat.
			createAbility({
				id = "teachMain",
                --Auto trigger means it triggers as soon as it played (other trigger options can be found in the Lua Doc)
				trigger = autoTrigger,
				effect = gainCombatEffect(4),
			}),
            --
            createAbility({
				id = "teachImperial",
                --triggers automatically, when played with an imperial card, because gaining health is mandatory by the game rules.
				trigger = autoTrigger,
				effect = healPlayerEffect(currentPid, 5),
                --This line defines which faction needs to be played with it to trigger this ability.
                allyFactions = {imperialFaction}
			}),
            --
            createAbility({
                id = "teachNecros",
                --requires player interaction to trigger
				trigger = uiTrigger,
                --the prompt is what you see when you click on a card to make it bigger to read it
				promptType = showPrompt,
                --The prompt layout does not automatically use the same layout as the card. Here they are forced to be the same thing.
				layout = cardLayout,
                --Draw 1 card when triggered.
                effect = drawCardsEffect(1),
                --This line defines which faction needs to be played with it to trigger this ability.
                allyFactions = {necrosFaction}
            }),
		}
	})
end

--=======================================================================================================
function endGame(g)
end

--=======================================================================================================


function setupMeta(meta)
    meta.name = "lesson_3"
    meta.minLevel = 0
    meta.maxLevel = 0
    meta.introbackground = ""
    meta.introheader = ""
    meta.introdescription = ""
    meta.path = "C:/Users/xTheC/Desktop/Git Repositories/Hero-Realms-Lua-Lessons/Lua Lesson #3/lesson_3.lua"
     meta.features = {
}

end